search-paths:
  - ../service/target/wasm32-unknown-unknown/release
  - ../service/target/wasm32-wasi/release
  - ../middleware/target/wasm32-unknown-unknown/release
  - ../middleware/target/wasm32-wasi/release

instantiations:
  $input:
    arguments:
      downstream: svc
